name: Manual Generate Android APK
on:
  workflow_dispatch:
    inputs:

      buildVariant:
        type: choice
        description: 'Build Variant'
        required: true
        default: 'NormalOptimized'
        options: 
        - NormalOptimized
        - NormalDebug
        - VrDebug
        - VrOptimized

jobs:

  apk:
    name: Generate ${{ github.event.inputs.buildVariant }} APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Fetch tags
        run: |
          git fetch --deepen=15000 --no-recurse-submodules --tags || exit 0

      - name: Set Env Var(s)
        run: |
          echo "GIT_VERSION=$(git describe --always)" >> $GITHUB_ENV
        
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
        
      #- name: Setup SDK
      #  uses: android-actions/setup-android@v3
          
      #- name: Setup NDK
      #  uses: nttld/setup-ndk@v1
      #  with:
      #    ndk-version: r21e

      - name: Test androidGitVersion
        run: gradle --quiet androidGitVersion
      
      - name: Assemble APK
        run: ./gradlew assemble${{ github.event.inputs.buildVariant }} --stacktrace
      
      #- name: Gradle Test
      #  run: bash ./gradlew test${{ github.event.inputs.buildVariant }}UnitTest --stacktrace
      
      - name: Package build
        run: |
          find . -name "*.apk"
          mkdir ppsspp
          if [ -e android/build/*/apk/*/*/*.apk ]; then
            cp android/build/*/apk/*/*/*.apk ppsspp/
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-${{ github.event.inputs.buildVariant }} build
          path: ppsspp/
